server:
  port: 5555

logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
        hibernate: DEBUG
        data:
          jpa: DEBUG
    com:
      mycode:
        foodorderapp: INFO


mysql:
  url: jdbc:mysql://localhost:3306/food-order-mysql
  username: root
  password: root
  driver: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true

mongodb:
  url: mongodb://localhost:27017/food-order-mongodb