spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/graphql
      username: postgres
      password: root
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQL9Dialect
            ddl-auto: update

# Graphql
graphql:
   servlet:
      mapping: /api/graphql
   playground:
      headers:
         Authentication: Bearer TOKEN
      tabs:
         - name: Sample Query
           query: classpath:graphql/playground/sample_query.graphql
           variable: classpath:graphql/playground/sample_variable.json
